# Generated by Django 2.1.3 on 2018-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credits',
            field=models.IntegerField(default=5),
        ),
    ]
